---
title: "02032021.RMD"
author: "Angie Boysen"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(cowplot)
library(PaletteWoodsHole)
library(RColorBrewer)
library(tidytuesdayR)
```
The Data

The data this week comes from FiveThirtyEight. They have a corresponding article on the topic. Note that the original source was superbowl-ads.com. You can watch all the ads via the FiveThirtyEight article above. 
```{r echo=FALSE}
tuesdata <- tidytuesdayR::tt_load('2021-03-02')
youtube <- tuesdata$youtube
```

Explore data

```{r explore, echo=FALSE}
unique(youtube$year)
table(youtube$brand)

youtube %>%
  mutate(fc_L_DL = like_count/dislike_count,
         provoking = (like_count+dislike_count)/view_count) %>%
  ggplot(.) +
  geom_point(aes(x=provoking, y = fc_L_DL, color = brand,
                 size = log10(view_count)),
             alpha = 0.3) +
  facet_wrap(~animals) +
  theme_bw() +
  scale_color_brewer(palette = 'Paired') +
  xlab("Percent provoked") +
  ylab("Fold Change (Likes/Dislikes)")

youtube %>%
  mutate(fc_L_DL = like_count/dislike_count,
         provoking = (like_count+dislike_count)/view_count) %>%
  dplyr::select(year, brand, funny, patriotic, 
                celebrity, danger, animals,
                use_sex, view_count, like_count, dislike_count,
                fc_L_DL, provoking) %>%
  gather(Category, Value, -view_count, -like_count,
         - dislike_count, -fc_L_DL, -provoking) %>%
  filter(Category != "year") %>%
  ggplot(.) +
  geom_density(aes(provoking, fill = Value),
               alpha = 0.2) +
  facet_wrap(~Category) +
  theme_bw() +
  xlab("Fraction of viewers provoked to like or dislike the ad") +
  ylab("density")

ggsave("02032021_superbowl_commercials.png")
```

## final plot
```{r echo=FALSE}

```

